# Generated by Django 4.2.9 on 2024-01-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='passport',
        ),
    ]
