# Generated by Django 4.2.9 on 2024-01-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_remove_delegate_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='passport',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
