# Generated by Django 4.2.9 on 2024-01-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_delegate_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='diet_restrictions',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='position',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='reasons_to_attend',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='spicy_food',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='vegan',
        ),
    ]
