# Generated by Django 4.2.9 on 2024-01-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_remove_delegate_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='allergies',
            field=models.ManyToManyField(to='registrations.allergies'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='diet_restrictions',
            field=models.ManyToManyField(to='registrations.diet'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='entity',
            field=models.ManyToManyField(to='registrations.entity'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='position',
            field=models.ManyToManyField(to='registrations.position'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='reasons_to_attend',
            field=models.ManyToManyField(to='registrations.reasontoattend'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='spicy_food',
            field=models.ManyToManyField(to='registrations.spicy'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='vegan',
            field=models.ManyToManyField(to='registrations.vegan'),
        ),
    ]
