# Generated by Django 4.2.9 on 2024-02-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_delegate_allergies_delegate_diet_restrictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
