# Generated by Django 4.2.9 on 2024-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_remove_delegate_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='allergies',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Checkin', 'Checkin')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='diet_restrictions',
            field=models.CharField(choices=[('Sugar Free', 'Sugar Free'), ('Oil Free', 'Oil Free')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='entity',
            field=models.CharField(choices=[('EGYPT', 'EGYPT'), ('ITALY', 'ITALY'), ('TURKEY', 'TURKEY')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='reasons_to_attend',
            field=models.CharField(choices=[('IRs', 'IRs'), ('Connections', 'Connections')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='spicy_food',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='vegan',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
    ]
