# Generated by Django 4.2.9 on 2024-02-03 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_delegate_allergies_delegate_diet_restrictions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegate',
            old_name='phone',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='email',
            new_name='aiesec_email',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='spicy_food',
            new_name='merchandise',
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='vegan',
            new_name='pre_and_post_trips',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='diet_restrictions',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='reasons_to_attend',
        ),
        migrations.AddField(
            model_name='delegate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='delegate',
            name='current_living_country',
            field=models.CharField(choices=[('EGYPT', 'EGYPT'), ('ITALY', 'ITALY'), ('TURKEY', 'TURKEY')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='expectation_from_cc_team',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='expectation_from_egyptian_nights',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='name_as_per_passport',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='natonality',
            field=models.CharField(choices=[('EGYPT', 'EGYPT'), ('ITALY', 'ITALY'), ('TURKEY', 'TURKEY')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='nick_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='passport_expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='passport_issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='passport_scanned_photo',
            field=models.ImageField(null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='passport_size_picture_of_the_candidate',
            field=models.ImageField(null=True, upload_to='delegates_photos/'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='personal_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='place_of_birth',
            field=models.CharField(choices=[('EGYPT', 'EGYPT'), ('ITALY', 'ITALY'), ('TURKEY', 'TURKEY')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='region',
            field=models.CharField(choices=[('MEA', 'MEA'), ('EUROPE', 'EUROPE'), ('AMERICAS', 'AMERICAS'), ('ASIA PACIFIC', 'ASIA PACIFIC')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='telegram_username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='whatsapp_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='workshops_with_partners',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='allergies',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
