# Generated by Django 4.2.9 on 2024-02-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_rename_phone_delegate_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Please select your gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='aiesec_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='current_living_country',
            field=models.CharField(blank=True, choices=[(None, 'Please select your living country'), ('Egypt', 'Egypt'), ('Italy', 'Italy'), ('Turkey', 'Turkey')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='entity',
            field=models.CharField(blank=True, choices=[(None, 'Please select your entity'), ('Egypt', 'Egypt'), ('Italy', 'Italy'), ('Turkey', 'Turkey')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='expectation_from_cc_team',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='expectation_from_egyptian_nights',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='merchandise',
            field=models.CharField(blank=True, choices=[(None, 'Are you interested?'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='name_as_per_passport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='natonality',
            field=models.CharField(blank=True, choices=[(None, 'Please select your nationality'), ('Egypt', 'Egypt'), ('Italy', 'Italy'), ('Turkey', 'Turkey')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='passport_scanned_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='passport_size_picture_of_the_candidate',
            field=models.ImageField(blank=True, null=True, upload_to='delegates_photos/'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='place_of_birth',
            field=models.CharField(blank=True, choices=[(None, 'Please select your place of birth'), ('Egypt', 'Egypt'), ('Italy', 'Italy'), ('Turkey', 'Turkey')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='position',
            field=models.CharField(blank=True, choices=[(None, 'Please select your position'), ('MCP', 'MCP'), ('MCVP', 'MCVP'), ('LCP', 'LCP')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='pre_and_post_trips',
            field=models.CharField(blank=True, choices=[(None, 'Are you interested?'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='region',
            field=models.CharField(blank=True, choices=[(None, 'Please select your region'), ('MEA', 'MEA'), ('Europe', 'Europe'), ('Americas', 'Americas'), ('Asia Pacific', 'Asia Pacific')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='workshops_with_partners',
            field=models.CharField(blank=True, choices=[(None, 'Are you interested?'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
    ]
