# Generated by Django 4.2.9 on 2024-02-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_rename_expectation_from_cc_team_delegate_agenda_expectations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegate',
            old_name='picture_of_the_candidate',
            new_name='picture_of_the_delegate',
        ),
    ]
