# Generated by Django 4.2.9 on 2024-02-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_rename_picture_of_the_candidate_delegate_picture_of_the_delegate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegate',
            old_name='current_living_country',
            new_name='current_living_country_territory',
        ),
    ]
