# Generated by Django 4.2.9 on 2024-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_rename_current_living_country_delegate_current_living_country_territory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='delegate',
            name='covid_certificate',
            field=models.CharField(blank=True, choices=[(None, '-------'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='food',
        ),
        migrations.AlterField(
            model_name='delegate',
            name='merchandise',
            field=models.CharField(blank=True, choices=[(None, '-------'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='pre_and_post_trips',
            field=models.CharField(blank=True, choices=[(None, '-------'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='visa_support',
            field=models.CharField(blank=True, choices=[(None, '-------'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='workshops_with_partners',
            field=models.CharField(blank=True, choices=[(None, '-------'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='food',
            field=models.ManyToManyField(to='registrations.food'),
        ),
    ]
