# Generated by Django 4.2.9 on 2024-02-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_rename_covid_certificate_delegate_room_with_the_same_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='workshops_with_partners',
        ),
    ]
