# Generated by Django 4.2.9 on 2024-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_remove_delegate_workshops_with_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='pre_and_post_trips',
            field=models.CharField(blank=True, choices=[(None, 'Please select your trips preference'), ('Pre-conference trip', 'Pre-conference trip'), ('Post-conference trip', 'Post-conference trip'), ('Both', 'Both'), ('None', 'None'), ('Lactose Intolerant', 'Lactose Intolerant'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
