# Generated by Django 4.2.9 on 2024-02-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_alter_delegate_pre_and_post_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='generation',
            field=models.CharField(blank=True, choices=[(None, 'Please select your generation'), ('23.24', '23.24'), ('24.25', '24.25')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='pre_and_post_trips',
            field=models.CharField(blank=True, choices=[(None, 'Please select your trips preference'), ('Pre-conference trip', 'Pre-conference trip'), ('Post-conference trip', 'Post-conference trip'), ('Both', 'Both'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
