# Generated by Django 4.2.9 on 2024-02-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_engagement_delegate_career_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegate',
            old_name='room_with_the_same_gender',
            new_name='room_preference',
        ),
    ]
