# Generated by Django 4.2.9 on 2024-02-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_remove_delegate_engagements_delete_engagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
