# Generated by Django 4.2.9 on 2024-04-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_delegate_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='agenda_expectations',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='cc_team_expecations',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='current_living_country_territory',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='egyptian_nights_expectations',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='food',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='logistical_expectations',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='merchandise',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='name_as_per_passport',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='natonality',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='passport_expiry_date',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='passport_issue_date',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='passport_scanned_photo',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='pre_and_post_trips',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='room_preference',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='visa_support',
        ),
    ]
