# Generated by Django 4.2.9 on 2024-04-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_remove_delegate_agenda_expectations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='picture_of_the_delegate',
        ),
    ]
